name: Build Release

on:
  push:
    tags:
      - "v*" # Trigger the workflow on new tags starting with 'v'
  workflow_dispatch:

jobs:
  release:
    name: Create Release

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        architecture: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: |
          go build -o pup-${{ matrix.os }}-${{ matrix.architecture }}

      - name: Get Tag from Git Reference
        id: get_tag
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | sed -n 's/refs\/tags\///p')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Describe your release here.

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pup-${{ matrix.os }}-${{ matrix.architecture }}
          asset_name: pup-${{ matrix.os }}-${{ matrix.architecture }}
          asset_content_type: application/octet-stream
